#requires -Version 5.1

<#
.SYNOPSIS
  Creates a set of sibling git worktrees for a Customs task, including a
  worktree of cargowise-allagents, so Claude (or any allagents-managed
  client) gets full CLAUDE.md/.claude/.agents skill coverage when started
  from the new location.

.DESCRIPTION
  cargowise-allagents' CLAUDE.md, .claude/, and .agents/ are generated by
  `npx allagents update` from .allagents/workspace.yaml, which references
  sibling repos by relative path (../CargoWise, ../CargoWise.Shared, ...).
  Those generated files are gitignored, so:
    - a plain `git worktree add` of CargoWise alone has no sibling
      cargowise-allagents at all, and
    - a worktree of cargowise-allagents alone carries its tracked
      workspace.yaml, but not the generated skill files, and its relative
      paths still point at the OLD sibling checkouts.

  This function creates a task folder (default:
  <WorkspaceRoot>\worktrees\<Task>) containing a worktree of
  cargowise-allagents plus a worktree of each repo you name, all as siblings
  using the folder names workspace.yaml expects, then runs
  `npx allagents update` inside the new cargowise-allagents worktree to
  regenerate the skill files for that sibling layout.

.PARAMETER Task
  Short task id used as the branch suffix and worktree folder name, e.g. WI00123456.

.PARAMETER Repos
  Repo folder names (siblings of cargowise-allagents under WorkspaceRoot) to
  worktree alongside it. Defaults to the repos listed in workspace.yaml.

.PARAMETER BaseBranch
  Branch to fork each worktree from. If omitted, each repo uses its own
  default: master for CargoWise, CargoWise.Shared, CargoWise.Customs; main
  for every other repo (cargowise-allagents, Customs.Specifications,
  Customs.Content). Pass this to override and force the same branch name
  for every repo.

.PARAMETER WorkspaceRoot
  Parent folder containing the existing repo checkouts. Default:
  C:\git\GitHub\WiseTechGlobal.

.PARAMETER StartClaude
  Launch `claude` in the new cargowise-allagents worktree once set up.

.EXAMPLE
  New-CargowiseAgentsWorktree -Task WI00123456

.EXAMPLE
  New-CargowiseAgentsWorktree -Task WI00123456 -Repos CargoWise,CargoWise.Customs -StartClaude

.NOTES
  After this, if you build/test inside the CargoWise or CargoWise.Shared
  worktree, run the cw-worktree-bin-sync preflight (their Bin/ starts empty).
#>
function New-CargowiseAgentsWorktree {
	[CmdletBinding(SupportsShouldProcess)]
	param(
		[Parameter(Mandatory)]
		[ValidatePattern('^[A-Za-z0-9_.-]+$')]
		[string]$Task,

		[string[]]$Repos = @('CargoWise', 'CargoWise.Shared', 'CargoWise.Customs', 'Customs.Specifications', 'Customs.Content'),

		[string]$BaseBranch,

		[string]$WorkspaceRoot = 'C:\git\GitHub\WiseTechGlobal',

		[switch]$StartClaude
	)

	$ErrorActionPreference = 'Stop'

	# CargoWise, CargoWise.Shared, and CargoWise.Customs default to 'master';
	# every other repo (cargowise-allagents, Customs.Specifications,
	# Customs.Content, ...) defaults to 'main'. -BaseBranch overrides this for
	# every repo when supplied.
	$masterBranchRepos = @('CargoWise', 'CargoWise.Shared', 'CargoWise.Customs')

	function Get-DefaultBranch {
		param([string]$RepoName)

		if ($BaseBranch) { return $BaseBranch }
		if ($masterBranchRepos -contains $RepoName) { return 'master' }
		return 'main'
	}

	$taskRoot = Join-Path $WorkspaceRoot 'worktrees' $Task
	New-Item -ItemType Directory -Path $taskRoot -Force | Out-Null

	function Add-RepoWorktree {
		param([string]$RepoName)

		$sourceRepo = Join-Path $WorkspaceRoot $RepoName
		if (-not (Test-Path (Join-Path $sourceRepo '.git'))) {
			Write-Warning "Skipping '$RepoName' - not found at $sourceRepo"
			return
		}

		# Drop stale worktree registrations (e.g. the folder was deleted manually
		# after a previous partial run) so branch/path checks below are accurate.
		& git -C $sourceRepo worktree prune 2>$null | Out-Null

		$dest = Join-Path $taskRoot $RepoName
		if (Test-Path $dest) {
			Write-Host "Worktree already exists: $dest" -ForegroundColor DarkGray
			return
		}

		$repoBaseBranch = Get-DefaultBranch -RepoName $RepoName
		$branch = "$Task/$RepoName"
		& git -C $sourceRepo rev-parse --verify --quiet "refs/heads/$branch" 2>$null | Out-Null
		$branchExists = $LASTEXITCODE -eq 0

		if ($branchExists) {
			# Branch survived a previous partial run (e.g. it succeeded but a
			# later step in the script failed). Reuse it instead of failing on
			# "branch already exists".
			Write-Host "Creating worktree: $RepoName -> $dest (reusing existing branch $branch)" -ForegroundColor Cyan
			& git -C $sourceRepo worktree add $dest $branch
		}
		else {
			Write-Host "Creating worktree: $RepoName -> $dest (branch $branch, from $repoBaseBranch)" -ForegroundColor Cyan
			& git -C $sourceRepo fetch origin $repoBaseBranch 2>$null | Out-Null
			& git -C $sourceRepo worktree add -b $branch $dest "origin/$repoBaseBranch"
		}
	}

	# cargowise-allagents first - its .allagents/workspace.yaml is tracked in git,
	# so it comes along for free with the worktree.
	Add-RepoWorktree -RepoName 'cargowise-allagents'

	foreach ($repo in $Repos) {
		Add-RepoWorktree -RepoName $repo
	}

	$agentsWorktree = Join-Path $taskRoot 'cargowise-allagents'
	if (Test-Path $agentsWorktree) {
		Write-Host "Regenerating .agents/.claude/CLAUDE.md for the new sibling layout..." -ForegroundColor Cyan
		Push-Location $agentsWorktree
		try {
			& npx allagents update
		}
		finally {
			Pop-Location
		}
	}

	Write-Host "`nTask workspace ready: $taskRoot" -ForegroundColor Green
	Write-Host "Start Claude from: $agentsWorktree" -ForegroundColor Green
	Write-Host "Cleanup when done: git worktree remove <path>  (and 'git branch -D <branch>' per repo)" -ForegroundColor DarkGray

	if ($StartClaude -and (Test-Path $agentsWorktree)) {
		Push-Location $agentsWorktree
		try { & claude } finally { Pop-Location }
	}
}
