#requires -Version 5.1

<#
.SYNOPSIS
  Creates a set of sibling git worktrees for a Customs task, including a
  worktree of cargowise-allagents, so Claude (or any allagents-managed
  client) gets full CLAUDE.md/.claude/.agents skill coverage when started
  from the new location.

.DESCRIPTION
  cargowise-allagents' CLAUDE.md, .claude/, and .agents/ are generated by
  `npx allagents update` from .allagents/workspace.yaml, which references
  sibling repos by relative path (../CargoWise, ../CargoWise.Shared, ...).
  Those generated files are gitignored, so:
    - a plain `git worktree add` of CargoWise alone has no sibling
      cargowise-allagents at all, and
    - a worktree of cargowise-allagents alone carries its tracked
      workspace.yaml, but not the generated skill files, and its relative
      paths still point at the OLD sibling checkouts.

  This function creates a task folder (default:
  <WorkspaceRoot>\worktrees\<Task>) containing a worktree of
  cargowise-allagents plus a worktree of each repo you name, all as siblings
  using the folder names workspace.yaml expects, then runs
  `npx allagents update` inside the new cargowise-allagents worktree to
  regenerate the skill files for that sibling layout.

.PARAMETER WorkItem
  Work item number, e.g. WI00123456. Used in the branch name and folder name.

.PARAMETER Description
  Short slug describing the feature so worktrees are easy to tell apart, e.g.
  fix-duty-calc. Used in the branch name and folder name.

.PARAMETER Repos
  Repo folder names (siblings of cargowise-allagents under WorkspaceRoot) to
  worktree alongside it. Defaults to the repos listed in workspace.yaml.

.PARAMETER BaseBranch
  Branch to fork each worktree from. If omitted, each repo uses its own
  default: master for CargoWise, CargoWise.Shared, CargoWise.Customs; main
  for every other repo (cargowise-allagents, Customs.Specifications,
  Customs.Content). Pass this to override and force the same branch name
  for every repo.

.PARAMETER WorkspaceRoot
  Parent folder containing the existing repo checkouts. Default:
  C:\git\GitHub\WiseTechGlobal.

.PARAMETER StartClaude
  Launch `claude` in the new cargowise-allagents worktree once set up.

.EXAMPLE
  New-CargowiseAgentsWorktree -WorkItem WI00123456 -Description fix-duty-calc

.EXAMPLE
  New-CargowiseAgentsWorktree -WorkItem WI00123456 -Description fix-duty-calc -Repos CargoWise,CargoWise.Customs -StartClaude

.NOTES
  After this, if you build/test inside the CargoWise or CargoWise.Shared
  worktree, run the cw-worktree-bin-sync preflight (their Bin/ starts empty).
#>
function New-CargowiseAgentsWorktree {
	[CmdletBinding(SupportsShouldProcess)]
	param(
		[Parameter(Mandatory, Position = 0)]
		[ValidatePattern('^[A-Za-z0-9_.-]+$')]
		[string]$WorkItem,

		[Parameter(Mandatory, Position = 1)]
		[ValidatePattern('^[A-Za-z0-9_.-]+$')]
		[string]$Description,

		[string[]]$Repos = @('CargoWise', 'CargoWise.Shared', 'CargoWise.Customs', 'Customs.Specifications', 'Customs.Content'),

		[string]$BaseBranch,

		[string]$WorkspaceRoot = 'C:\git\GitHub\WiseTechGlobal',

		[switch]$StartClaude
	)

	$ErrorActionPreference = 'Stop'

	# CargoWise, CargoWise.Shared, and CargoWise.Customs default to 'master';
	# every other repo (cargowise-allagents, Customs.Specifications,
	# Customs.Content, ...) defaults to 'main'. -BaseBranch overrides this for
	# every repo when supplied.
	$masterBranchRepos = @('CargoWise', 'CargoWise.Shared', 'CargoWise.Customs')

	function Get-DefaultBranch {
		param([string]$RepoName)

		if ($BaseBranch) { return $BaseBranch }
		if ($masterBranchRepos -contains $RepoName) { return 'master' }
		return 'main'
	}

	$branchName = "TT7/$WorkItem/$Description"
	# Nested Join-Path for Windows PowerShell 5.1 compatibility: its Join-Path
	# only takes -Path/-ChildPath (no third segment like PowerShell 7).
	$taskRoot = Join-Path (Join-Path $WorkspaceRoot 'worktrees') "$WorkItem-$Description"
	New-Item -ItemType Directory -Path $taskRoot -Force | Out-Null

	function Add-RepoWorktree {
		param([string]$RepoName)

		$sourceRepo = Join-Path $WorkspaceRoot $RepoName
		if (-not (Test-Path (Join-Path $sourceRepo '.git'))) {
			Write-Warning "Skipping '$RepoName' - not found at $sourceRepo"
			return
		}

		# Drop stale worktree registrations (e.g. the folder was deleted manually
		# after a previous partial run) so branch/path checks below are accurate.
		& git -C $sourceRepo worktree prune 2>$null | Out-Null

		$dest = Join-Path $taskRoot $RepoName
		if (Test-Path $dest) {
			Write-Host "Worktree already exists: $dest" -ForegroundColor DarkGray
			return
		}

		$repoBaseBranch = Get-DefaultBranch -RepoName $RepoName
		$branch = $branchName
		& git -C $sourceRepo rev-parse --verify --quiet "refs/heads/$branch" 2>$null | Out-Null
		$branchExists = $LASTEXITCODE -eq 0

		if ($branchExists) {
			# Branch survived a previous partial run (e.g. it succeeded but a
			# later step in the script failed). Reuse it instead of failing on
			# "branch already exists".
			Write-Host "Creating worktree: $RepoName -> $dest (reusing existing branch $branch)" -ForegroundColor Cyan
			& git -C $sourceRepo worktree add $dest $branch
		}
		else {
			Write-Host "Creating worktree: $RepoName -> $dest (branch $branch, from $repoBaseBranch)" -ForegroundColor Cyan
			& git -C $sourceRepo fetch origin $repoBaseBranch 2>$null | Out-Null
			& git -C $sourceRepo worktree add -b $branch $dest "origin/$repoBaseBranch"
		}
	}

	# cargowise-allagents first - its .allagents/workspace.yaml is tracked in git,
	# so it comes along for free with the worktree.
	Add-RepoWorktree -RepoName 'cargowise-allagents'

	foreach ($repo in $Repos) {
		Add-RepoWorktree -RepoName $repo
	}

	$agentsWorktree = Join-Path $taskRoot 'cargowise-allagents'
	if (Test-Path $agentsWorktree) {
		Write-Host "Regenerating .agents/.claude/CLAUDE.md for the new sibling layout..." -ForegroundColor Cyan
		Push-Location $agentsWorktree
		try {
			& npx allagents update
		}
		finally {
			Pop-Location
		}
	}

	Write-Host "`nTask workspace ready: $taskRoot" -ForegroundColor Green
	Write-Host "Start Claude from: $agentsWorktree" -ForegroundColor Green
	Write-Host "Cleanup when done: git worktree remove <path>  (and 'git branch -D <branch>' per repo)" -ForegroundColor DarkGray

	if ($StartClaude -and (Test-Path $agentsWorktree)) {
		Push-Location $agentsWorktree
		try { & claude } finally { Pop-Location }
	}
}

<#
.SYNOPSIS
  Interactively selects a task folder under the worktrees root and removes all
  git worktrees inside it, leaving the branches intact.

.DESCRIPTION
  Lists the task folders created by New-CargowiseAgentsWorktree (each folder
  under <WorkspaceRoot>\worktrees\ holds one sibling worktree per repo). You
  pick one; every repo worktree inside it is removed via
  `git worktree remove` against its source repo under WorkspaceRoot. Branches
  are NOT deleted - only the worktree working directories and their
  registrations. The now-empty task folder is removed at the end.

.PARAMETER WorkspaceRoot
  Parent folder containing the source repo checkouts and the worktrees
  directory. Default: C:\git\GitHub\WiseTechGlobal.

.PARAMETER Force
  Pass through to `git worktree remove --force` so worktrees with
  uncommitted/untracked changes are still removed.

.EXAMPLE
  Remove-CargowiseAgentsWorktree

.EXAMPLE
  Remove-CargowiseAgentsWorktree -Force
#>
function Remove-CargowiseAgentsWorktree {
	[CmdletBinding(SupportsShouldProcess)]
	param(
		[string]$WorkspaceRoot = 'C:\git\GitHub\WiseTechGlobal',

		[switch]$Force
	)

	$ErrorActionPreference = 'Stop'

	$worktreesRoot = Join-Path $WorkspaceRoot 'worktrees'
	if (-not (Test-Path $worktreesRoot)) {
		Write-Warning "No worktrees folder found at: $worktreesRoot"
		return
	}

	$taskFolders = @(Get-ChildItem -Path $worktreesRoot -Directory | Sort-Object Name)
	if ($taskFolders.Count -eq 0) {
		Write-Host "No task folders under: $worktreesRoot" -ForegroundColor DarkGray
		return
	}

	Write-Host "Task folders under $worktreesRoot" -ForegroundColor Cyan
	for ($i = 0; $i -lt $taskFolders.Count; $i++) {
		Write-Host ("  [{0}] {1}" -f ($i + 1), $taskFolders[$i].Name)
	}

	$choice = Read-Host "Select a folder to remove (1-$($taskFolders.Count), or blank to cancel)"
	if ([string]::IsNullOrWhiteSpace($choice)) {
		Write-Host 'Cancelled.' -ForegroundColor DarkGray
		return
	}

	$index = 0
	if (-not [int]::TryParse($choice, [ref]$index) -or $index -lt 1 -or $index -gt $taskFolders.Count) {
		Write-Warning "Invalid selection: $choice"
		return
	}

	$taskFolder = $taskFolders[$index - 1]
	$repoFolders = @(Get-ChildItem -Path $taskFolder.FullName -Directory | Sort-Object Name)
	if ($repoFolders.Count -eq 0) {
		Write-Host "No repo worktrees inside: $($taskFolder.FullName)" -ForegroundColor DarkGray
	}

	foreach ($repoFolder in $repoFolders) {
		$sourceRepo = Join-Path $WorkspaceRoot $repoFolder.Name
		if (-not (Test-Path (Join-Path $sourceRepo '.git'))) {
			Write-Warning "Source repo not found for '$($repoFolder.Name)' at $sourceRepo - skipping"
			continue
		}

		if ($PSCmdlet.ShouldProcess($repoFolder.FullName, 'git worktree remove')) {
			Write-Host "Removing worktree: $($repoFolder.FullName)" -ForegroundColor Cyan
			$removeArgs = @('-C', $sourceRepo, 'worktree', 'remove', $repoFolder.FullName)
			if ($Force) { $removeArgs += '--force' }
			& git @removeArgs
			& git -C $sourceRepo worktree prune 2>$null | Out-Null
		}
	}

	# Remove the task folder if it's now empty (git worktree remove deletes the
	# worktree dirs; this cleans up any leftover scaffolding).
	if ((Test-Path $taskFolder.FullName) -and
		(@(Get-ChildItem -Path $taskFolder.FullName -Force).Count -eq 0) -and
		$PSCmdlet.ShouldProcess($taskFolder.FullName, 'Remove empty task folder')) {
		Remove-Item -Path $taskFolder.FullName -Force
	}

	Write-Host "`nDone. Branches were left intact." -ForegroundColor Green
}
